# Generated by Django 2.1 on 2019-05-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_video', models.CharField(blank=True, default='hello', help_text='просто текст', max_length=100, null=True, verbose_name='видео')),
            ],
        ),
    ]
